- name: installing package with loops
  hosts: local
  become: yes
  tasks:
    - name: installing package
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
      - nginx
      - mysql-server
      - zip